config/routes.rb
Rails.application.routes.draw do
  resources :habits do
    post :check_in
  end

  resources :habit_records
  root to: "habits#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :habit
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
  belongs_to :habit
  validate :only_one_check_in_per_day, on: :create

  def only_one_check_in_per_day
    beginning_of_day = self.checked_in_on.beginning_of_day
    end_of_day = self.checked_in_on.end_of_day

    if(CheckIn.where("checked_in_on BETWEEN ? and ?", beginning_of_day, end_of_day)
                  .where(habit_id: self.habit_id)
                  .exists?)
      errors.add(:checked_in_on, "can only be done once per day")
    end
  end
end

app/models/habit.rb
class Habit < ApplicationRecord
  has_many :check_ins
  has_many :streaks
  has_many :badges
end

app/models/habit_record.rb
class HabitRecord < ApplicationRecord
  belongs_to :habit
  validate :only_one_check_in_per_day, on: :create

  def only_one_check_in_per_day
    beginning_of_day = self.checked_in_on.beginning_of_day
    end_of_day = self.checked_in_on.end_of_day

    if(HabitRecord.where("checked_in_on BETWEEN ? and ?", beginning_of_day, end_of_day)
                  .where(habit_id: self.habit_id)
                  .exists?)
      errors.add(:checked_in_on, "can only be done once per day")
    end
  end
end

app/models/streak.rb
class Streak < ApplicationRecord
  belongs_to :habit
  validates :start_date, presence: true

  def self.running
    self.where(end_date: nil)
  end

  def self.currently_running
    running.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  def new
    @habit = Habit.new
  end

  def create
    Habit.create(habit_params)
    redirect_to root_path
  end

  def index
    @habits = Habit.all
    @today_date = Date.today.strftime("%Y-%m-%d")
  end

  def check_in
    @habit = Habit.find(params[:habit_id])
    manager = StreakManager.new(habit: @habit)
    manager.check_in(check_in_type: params[:check_in_type])
    redirect_to root_path, notice: manager.errors
  end

  private

  def habit_params
    params.require(:habit).permit(:name, :habit_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/habits/_badges.haml
- if habit.badges.present?
  %span.crushed
    You crushed:
  %span.badge
    = habit.badges.first.name.strip

app/views/habits/index.haml
= link_to "Add a habit to track", new_habit_path, class: "action"
%h1 Today's Habits
%h3.indent= @today_date
%ul.no-style
  - @habits.each do |habit|
    - streak_manager = StreakManager.new(habit: habit)
    %li{id: "habit#{habit.id}"}
      %span{class: "#{habit.habit_type} tag"}
        = habit.habit_type
      %span.habit-in-list
        = habit.name
      = link_to habit_check_in_path(habit_id: habit.id, checked_in_on: DateTime.now, check_in_type: "crushed"), method: :post, class: "check-in" do
        = icon "fas", "fist-raised", class: "crushed"
      = "Going for #{streak_manager.current_streak_count} days"
      = render partial: "badges", locals: { habit: habit }

app/views/habits/new.haml
%h2 New Habit to Track
= form_for @habit do |f|
  .field_group
    = f.label :name, class: "horizontal"
    = f.text_field :name, class: "horizontal"
  .field_group
    = f.label :habit_type, class: "horizontal"
    = f.select :habit_type, [["Don't do it", "dont-do-it"], ["Do it","do-it"]]
  .submit
    = f.submit class: "action"

app/views/layouts/_alert.haml
- flash.each do |key, value|
  =raw value if value.present?

app/views/layouts/_head.html.haml
%head
  %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=EmulateIE8"}
  %title= content_for?(:title) ? yield(:title) : "Habits"
  = stylesheet_link_tag :application, :media => "all"
  = javascript_include_tag :application
  %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0", :name => "viewport"}
  %meta{:content => "IE=8", "http-equiv" => "X-UA-Compatible"}
  = csrf_meta_tags

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/head'
  %body
    .container
      = render "layouts/alert"
      .main-business
        = yield